version: '3.0'

services:
    db:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: mysql.kanban-board.docker
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        volumes:
            - mysql.kanban-board.docker:/var/lib/mysql
        ports:
            - 127.0.0.1:${DATABASE_PORT}:3306

volumes:
    mysql.kanban-board.docker:
